---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: targets/nl1-rocklor
    repoURL: https://github.com/ben-obrien/ap-argocd-config-ext
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true