---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-k3s-server
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  source:
    path: targets/nl1-decklor
    repoURL: https://github.com/ben-obrien/ap-k3s-server-config-ext
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
