---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/application_config-k3s-server.yaml
- resources/application_config-ocp.yaml
- resources/application_config-vsphere.yaml
